### ISSUE TITLE
Odeljak za vestine i tehnologije

### ISSUE THREAD

**Issue by n-ratinac** [iLiciLi/portfolio#3]
Ucitaces iz nekog .json podatke o svojim vestinama. Za svaku vestinu je poznato:

1. Godina iskustva
2. Ocena (0 ... 10)
3. Naziv

Filtracija vestina na osnovu broja zvezdica (tipa ne manje od 3, ne manje od 5 itd.)

Dugme za reset filtracije.

**Comment by iLiciLi** [comment]
FIltracija i dugme za reset filtracije su ubačeni.

Link commit-a koji je rešio ovaj zadatak : [Rešenje ovog issue-a](https://github.com/iLiciLi/portfolio/commit/4500dead3877650cd03a54ab5484cdc86efad12d)

**Comment by iLiciLi** [comment]
FIltracija i dugme za reset filtracije su ubačeni.

Link commit-a koji je rešio ovaj zadatak : [Rešenje ovog issue-a](https://github.com/iLiciLi/portfolio/commit/4500dead3877650cd03a54ab5484cdc86efad12d)

**Comment by n-ratinac** [comment]
Sjajno odradjeno. Lepo si se odomacio u vanilla JS-u, verujem da ces biti jos bolji kada krenes JQuery da koristis.
